### ISSUE TITLE
Thoughts on Parameters

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/BlueTeamScripts#1]
I checked out the all the parameters and ParameterSets you have going on and think there might be a way or two to simplify them.

Some ideas:
1. You could remove all the `[Switch]` parameters and leave the `[String]`s in their ParameterSets and make them all Mandatory. Then to determine which function you wish to execute, you could leverage the `$PSCmdlet.ParameterSetName` variable.
2. Could consolidate `$TargetTXTFile` and `$TargetCSVFile` into `$TargetFile`  and create logic around handling both:
```
try {
    $Computers = Import-Csv $TargetFile -ErrorAction Stop
} catch {
    $Computers = Get-Content $TargetFile
}
```

**Comment by 5ynax** [comment]
implemented
