### ISSUE TITLE
Host List Building

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/BlueTeamScripts#10]
I like all the try-catch blocks here, but you want to be careful with halfheartedly sent errors from other cmdlets (Write-Error is by default not terminating). If you add `-ErrorAction Stop` you can explicitly tell these cmdlets you want them to terminate on any kind of error.

**Comment by 5ynax** [comment]
Added -ErrorAction Stop where needed to force catching of errors.
