### ISSUE TITLE
ActiveDirectory PowerShell Module Requirement

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/BlueTeamScripts#11]
I see you are using the ActiveDirectory PowerShell Module cmdlets (which are awesome!) but I don't see a check anywhere to make sure those cmdlets are available to the user. Something like: 
```
if (!(Get-Command 'Get-ADComputer')) {
    Import-Module 'ActiveDirectory' -ErrorAction 'Stop'
}
```

**Comment by 5ynax** [comment]
Added
