### ISSUE TITLE
Scope-File function

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/BlueTeamScripts#2]
I found a few issues with the `Scope-File` function (newline escape characters switched to backslashes for markdown formatting):
1. Formatting the array for the CSV output, undeclared variable `$Path` in `$FilePathArray += "$Path\n"`
- If you are trying to make a single string with values separated by newlines, you could use `$FilePathEval -Join "\n"`
2. Smaller code reduction thing: you could move one of the `return [PSCustomObject]$OutHash` lines below the if-else check and remove the other one. Since you're setting up `$OutHash` in both branches of the conditional statement, it will have something to return at the end

**Comment by 5ynax** [comment]
optimization made.
