### ISSUE TITLE
Scope-IPAddress function

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/BlueTeamScripts#4]
I found some potential improvements with the `Scope-IPAddress` function:
1. Do you want to add some flags to the vanilla `netstat` call?
2. The object returned from `Select-String` is a funky MatchInfo object that isn't really string. Misleading when you are testing at on a session since that's what it looks like you're dealing with. I would switch this statement up to be `$IPAddressEval = netstat <flags?> | Select-String -Pattern ".*$Address.*" | Select-Object -ExpandProperty Matches | Select-Object -ExpandProperty Value`
3.  Code reduction opportunity: remove the if-else statement in favor of something like `$OutHash = @{ Host = $env:COMPUTERNAME; Detected=[Boolean]$IPAddressEval; Details = ($IPAddressEval -Join "\n") }`

**Comment by 5ynax** [comment]
implemented
