### ISSUE TITLE
Function Output Design Decision

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/BlueTeamScripts#5]
For a number of `Scope-*` functions, only a single result (object) is returned from the function which makes cramming multiline (or array) output into a field interesting. I could see the argument for wanting a single output object for each computer searched, but I would say the more PowerShell-friendly way to handle this is return each line of text that matches our scoping item as it's own object back up to the calling function.

Ex.
Rather than:
```
Host,Detected,Details
test-l1,true,"TCP 192.168.1.1 0.0.0.0 ...
              TCP 192.168.1.1 1.1.1.1 ..."
```
I would personally format it:
```
Host,Detection,Details
test-l1,true,"TCP 192.168.1.1 0.0.0.0 ..."
test-l1,true,"TCP 192.168.1.1 1.1.1.1 ..."
```

**Comment by 5ynax** [comment]
Talked this over. for now we are going to keep as is. if this becomes a problem, we will move to the other method.
