### ISSUE TITLE
Scope-Process function

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/BlueTeamScripts#6]
I found some potential improvements with the `Scope-Process` function:
1. Rather than looping through each `$ProcessEval` result as an individual `$Object` and adding values to special arrays, you could reference those attributes directly `$ProcessEval` with things like `$NameArray = $ProcessEval.Name` or `$EPArray = $ProcessEval.ExecutablePath`
2. Code reduction opportunity: remove the if-else statement in favor of something like `$OutHash = @{ Host = $env:COMPUTERNAME; Detected=[Boolean]$IPAddressEval; Name = $NameArray; ... }`

**Comment by 5ynax** [comment]
implemented.
