### ISSUE TITLE
Scope-Service function

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/BlueTeamScripts#7]
I found some potential improvements with the `Scope-Path` function:
1. Rather than looping through each `$ServiceEval` result as an individual `$Object` and adding values to special arrays, you could reference those attributes directly `$ServiceEval` with things like `$NameArray = $ServiceEval.Name` or `$DNArray = $ServiceEval.DisplayName`
2. Code reduction opportunity: remove the if-else statement in favor of something like `$OutHash = @{ Host = $env:COMPUTERNAME; Detected=[Boolean]$IPAddressEval; Name = $NameArray; ... }`

**Comment by 5ynax** [comment]
implemented.
