### ISSUE TITLE
Scope-LocalUsers function

### ISSUE THREAD

**Issue by valrkey** [Asymmetric-InfoSec/BlueTeamScripts#8]
I found some potential improvements with the `Scope-LocalUsers` function:
1. If the user doesn't exist on a system, the `Get-LocalUser` call will chuck some angry red text to the screen. Consider using an error action preference of `SilentlyContinue`
2. Rather than looping through each `$UserEval` result as an individual `$Object` and adding values to special arrays, you could reference those attributes directly `$UserEval` with things like `$NameArray = $UserEval.Name` or `$EPArray = $UserEval.ExecutablePath`
3. Code reduction opportunity: remove the if-else statement in favor of something like `$OutHash = @{ Host = $env:COMPUTERNAME; Detected=[Boolean]$IPAddressEval; Name = $NameArray; ... }`

**Comment by 5ynax** [comment]
implemented.
